(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)
(*                                                                             *)
(*         This file has been automatically generated by FeynRules.            *)
(*                                                                             *)
(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)


FR$ModelInformation={
  ModelName->"model"};

FR$ClassesTranslation={};

FR$InteractionOrderPerturbativeExpansion={};

FR$GoldstoneList={};

(*     Declared indices    *)

(*     Declared particles    *)

M$ClassesDescription = {
V[1] == {
    SelfConjugate -> True,
    PropagatorLabel -> B,
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> 0,
    Indices -> {} },

S[1] == {
    SelfConjugate -> True,
    PropagatorLabel -> S,
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> mS,
    Indices -> {} }
}


(*        Definitions       *)


mS[ ___ ] := mS;




(*      Couplings (calculated by FeynRules)      *)

M$CouplingMatrices = {

C[ S[1] , S[1] , S[1] ] == {{(-6*I)*kappa3, 0}, {(-2*I)*r51, 0}, {(-2*I)*r51, 0}, {(2*I)*r72, 0}, {(2*I)*r73, 0}, {(2*I)*r73, 0}, {(-2*I)*r51, 0}, {(2*I)*r72, 0}, {(2*I)*r73, 0}, {(2*I)*r72, 0}},

C[ S[1] , S[1] , S[1] , S[1] ] == {{(-24*I)*lmbd, 0}, {(-6*I)*r62, 0}, {(6*I)*r82, 0}, {(4*I)*c82, 0}, {(4*I)*c82, 0}, {(4*I)*c82, 0}, {(-6*I)*r62, 0}, {(4*I)*r83, 0}, {(6*I)*r82, 0}, {(4*I)*c82, 0}, {(4*I)*c82, 0}, {(-6*I)*r62, 0}, {(4*I)*r83, 0}, {(4*I)*r83, 0}, {(6*I)*r82, 0}, {(4*I)*c82, 0}, {(-6*I)*r62, 0}, {(4*I)*r83, 0}, {(4*I)*r83, 0}, {(4*I)*r83, 0}, {(6*I)*r82, 0}},

C[ S[1] , S[1] , S[1] , S[1] , S[1] ] == {{(120*I)*c51, 0}, {(-24*I)*r71, 0}, {(-24*I)*r71, 0}, {(-24*I)*r71, 0}, {(-24*I)*r71, 0}, {(-24*I)*r71, 0}},

C[ S[1] , S[1] , S[1] , S[1] , S[1] , S[1] ] == {{(720*I)*c61, 0}, {(-120*I)*r84, 0}, {(-120*I)*r84, 0}, {(-120*I)*r84, 0}, {(-120*I)*r84, 0}, {(-120*I)*r84, 0}, {(-120*I)*r84, 0}},

C[ S[1] , S[1] , S[1] , S[1] , S[1] , S[1] , S[1] ] == {{(5040*I)*c71, 0}},

C[ S[1] , S[1] , S[1] , S[1] , S[1] , S[1] , S[1] , S[1] ] == {{(40320*I)*c81, 0}}

}

